Diego
Jessir1108/electronic_design pull request #9
Opened 2023-09-10 21:12 UTC by DiegoCorroV

2023-09-10 21:18 UTC, Jessir1108 requested changes
Los errores de HEAD

2023-09-11 18:55 UTC, Jessir1108 approved these changes

2023-09-11 19:13 UTC, Yu4e approved these changes

2023-09-11 19:14 UTC, Yu4e approved these changes

2023-09-11 19:31 UTC, Yu4e approved these changes

2023-09-11 19:31 UTC, Yu4e approved these changes

2023-09-11 19:32 UTC, Yu4e approved these changes

2023-09-12 00:39 UTC, merged

2023-09-14 15:16 UTC, DiegoCorroV reviewed
Version con fondo naranja